#!/usr/bin/python
"""StarCraft II game module generator -- static-site build for the hotkey editor.

SC2 hotkeys are a `.SC2Hotkeys` INI (a sparse [Commands] override list).  --build inlines the
repo-root page.html shell + this game's module.js + the vendored dataset (data/sc2.json: default
bindings, command-card grid positions, names and grouping, generated by data/gen_sc2_data.py from
extracted LotV multiplayer game files) to produce site/starcraft2/index.html, then refreshes the
launcher across all built games.

There is no in-tool --regen: refreshing the dataset needs the extracted game files and is done by
running data/gen_sc2_data.py and data/gen_sc2_icons.py (see data/ and the project README).

Note the source folder is `games/Starcraft2/` (capitalised) but the slug -- and therefore the
`site/<slug>/` folder -- is lowercase `starcraft2`.

Stdlib only (works on Python 3.7).
"""
import glob
import json
import os
import shutil
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))            # games/Starcraft2/
_ROOT = os.path.dirname(os.path.dirname(_HERE))               # repo root
_GAME_SLUG = 'starcraft2'                                     # lowercase site/ slug
_GAME_NAME = 'StarCraft II'

sys.path.insert(0, _ROOT)                                     # for the shared page_assembler
import page_assembler                                         # noqa: E402


def build(copy_icons=True):
    """Assemble the self-contained site/starcraft2/index.html from page.html + module.js + data.

    Inlines data/sc2.json (units -> command cards -> buttons, with default keys + grid positions)
    plus data/sc2_icons.json (command -> icon url) for the module's setData.  Returns (slug, name)
    on success or None on failure -- the page_assembler.build_all contract.  copy_icons controls
    whether the (large, rarely-changed) icon folder is recopied into site/starcraft2/icons/;
    build_all passes it through from build.py's --icons flag.
    """
    page_path = os.path.join(_ROOT, 'page.html')
    module_path = os.path.join(_HERE, 'module.js')
    data_path = os.path.join(_HERE, 'data', 'sc2.json')
    icons_path = os.path.join(_HERE, 'data', 'sc2_icons.json')
    try:
        module_js = open(module_path, encoding='utf-8').read()
        with open(data_path, encoding='utf-8') as f:
            data = json.load(f)                  # { units: {...} }
    except FileNotFoundError as e:
        print('ERROR: missing %s' % e.filename)
        return None
    try:
        with open(icons_path, encoding='utf-8') as f:
            data['icons'] = json.load(f)         # command -> "icons/<file>.png" for the card overlay
        _warn_stale_icons(data)
    except FileNotFoundError:
        print('WARNING: %s missing; ability-icon overlay disabled' % os.path.basename(icons_path))
    # Bundled "recommended" ergonomic layout for the one-click "try my layout" box.  A .SC2Hotkeys
    # profile is plain INI text, so inline it verbatim (module.js loadRecommended parses it at
    # runtime, like loadDefault).  Optional: an empty/absent RecommendedLayout/ just hides the box.
    rec_dir = os.path.join(_HERE, 'HotkeyFiles', 'RecommendedLayout')
    rec_files = sorted(glob.glob(os.path.join(rec_dir, '*.SC2Hotkeys')))
    if rec_files:
        rec_path = rec_files[0]
        stem = os.path.splitext(os.path.basename(rec_path))[0]
        with open(rec_path, encoding='utf-8') as f:
            data['recommended'] = {'name': stem, 'text': f.read()}
    else:
        print('note: no .SC2Hotkeys in HotkeyFiles/RecommendedLayout/; "try my layout" box hidden')
    out_path = os.path.join(_ROOT, 'site', _GAME_SLUG, 'index.html')
    try:
        nbytes = page_assembler.assemble(page_path, data, out_path, module_js, _GAME_SLUG)
    except RuntimeError as e:
        print('ERROR: %s' % e)
        return None
    print('wrote site/%s/index.html (%d KB)' % (_GAME_SLUG, nbytes // 1024))
    if copy_icons:
        _copy_icons(os.path.dirname(out_path))
    return (_GAME_SLUG, _GAME_NAME)


def _warn_stale_icons(data):
    """Warn if any card button has an icon in the data but no entry in sc2_icons.json.

    module.js resolves overlays via ICONS[command] (iconOf), so a command missing from the
    map renders with no icon even though the art exists -- the classic symptom of a stale
    sc2_icons.json (a command was added to sc2.json after the icon map was last regenerated).
    Non-fatal: just flags the gap so `python3 data/gen_sc2_icons.py` gets re-run.
    """
    icons = data.get('icons') or {}
    missing = []
    for u in data.get('units', {}).values():
        for card in u.get('cards', []):
            for b in card.get('buttons', []):
                if b.get('icon') and b['command'] not in icons and b['command'] not in missing:
                    missing.append(b['command'])
    if missing:
        shown = ', '.join(missing[:5]) + ('...' if len(missing) > 5 else '')
        print('WARNING: %d command(s) have an icon but are missing from sc2_icons.json '
              '(stale map -- re-run data/gen_sc2_icons.py): %s' % (len(missing), shown))


def _copy_icons(out_dir):
    """Copy the converted ability icons next to the built page (site/starcraft2/icons/).

    The page can't inline the PNGs, so the module references them relatively (icons/<name>.png --
    see module.js iconOf / data/sc2_icons.json); this ships that folder alongside index.html so it
    works on any static host and when the file is opened straight off disk.  A plain overwriting
    copy so a removed source icon is pruned too.
    """
    src = os.path.join(_HERE, 'data', 'icons')
    if not os.path.isdir(src):
        print('WARNING: %s missing; no ability icons copied to site/' % os.path.relpath(src, _ROOT))
        return
    dst = os.path.join(out_dir, 'icons')
    if os.path.isdir(dst):
        shutil.rmtree(dst)
    shutil.copytree(src, dst)
    n = sum(len(files) for _, _, files in os.walk(dst))
    print('copied %d ability icons to site/%s/icons/' % (n, _GAME_SLUG))


if __name__ == '__main__':
    args = sys.argv[1:]
    if '--build' in args or not args:
        if build() is None:
            sys.exit(1)
        page_assembler.write_launcher_for_built(_ROOT)
        print('wrote site/index.html (launcher)')
        sys.exit(0)
    print(__doc__)
