// StarCraft II game module -- the SC2 half of the multi-game seam.
//
// Bindings are a `.SC2Hotkeys` profile: an INI with [Settings], [Hotkeys] and a [Commands]
// section of `Command=Key` / `Command/Unit=Key` lines.  Crucially the file is *sparse* -- it
// lists only the commands whose key DIFFERS from the game default; everything absent uses the
// built-in default.  So this module carries the full default set in its dataset (data/sc2.json,
// generated by data/gen_sc2_data.py from the extracted LotV multiplayer game files) and treats a
// loaded file as a patch over those defaults.  On save we write back only the differences.
//
// Like the AoE2/WC3 modules this is injected into the shell's main <script>, wrapped in the IIFE
// below so its internals stay private; it reaches outward only to register GAMES.starcraft2 and
// is driven by the engine solely through GAME.* (assembled at the bottom).
//
// Naming / grouping model:
//   * A command's binding identity is its output name: `Command` when the button is Universal
//     (one hotkey shared by every unit -- Move, Stop, Attack, Stim, ...) or `Command/Unit`
//     otherwise (a per-unit hotkey).  bindings() emits one *record* per on-card occurrence; all
//     occurrences of a universal command share one binding `id`, so an edit propagates everywhere
//     and the engine never conflicts a command with itself across cards.
//   * Universal commands are shown once in a "Common Commands" group; unit-specific commands are
//     grouped by their unit.  A unit group appears only when the unit has at least one
//     unit-specific command -- units whose card is only universal commands (a plain Marine) have
//     nothing of their own to rebind and fold entirely into Common, matching how SC2 works.
(function () {

// ===== SC2 key token <-> virtual-key code ========================================
// A [Commands] value is `[Mod+]...Key`, e.g. `Q`, `Shift+Q`, `Control+Alt+D`, `Escape`.
// Blank or `None` means unbound.  We map the base key token to the same VK codes the engine's
// keyboard uses (A-Z -> 65-90, 0-9 -> 48-57, specials via the table below); an unrecognised token
// is preserved verbatim so an exotic binding still round-trips even if the keyboard can't show it.
// SC2's own key-token spelling (from .SC2Hotkeys files): SemiColon / BracketOpen / BackSlash / ...
var SPECIAL_TO_VK = {
  Escape: 27, Space: 32, Tab: 9, Backspace: 8, Enter: 13, Return: 13,
  Grave: 192, Minus: 189, Equals: 187, BracketOpen: 219, BracketClose: 221, BackSlash: 220,
  SemiColon: 186, Apostrophe: 222, Comma: 188, Period: 190, Slash: 191,
  Delete: 46, Insert: 45, Home: 36, End: 35, PageUp: 33, PageDown: 34,
  Up: 38, Down: 40, Left: 37, Right: 39
};
var VK_TO_SPECIAL = {};
Object.keys(SPECIAL_TO_VK).forEach(function (k) { if (VK_TO_SPECIAL[SPECIAL_TO_VK[k]] == null) VK_TO_SPECIAL[SPECIAL_TO_VK[k]] = k; });
for (var _f = 1; _f <= 12; _f++) { SPECIAL_TO_VK['F' + _f] = 111 + _f; VK_TO_SPECIAL[111 + _f] = 'F' + _f; }
var MOD_TOKENS = { Shift: 'shift', Control: 'ctrl', Ctrl: 'ctrl', Alt: 'alt' };

// Parse a value string into { code, ctrl, alt, shift, raw }.  A value can hold several
// comma-separated bindings (SC2 allows multiple keys per command, e.g. `Larva=0,P,SemiColon`);
// we edit the FIRST and the codec preserves the rest on save. `raw` holds the literal base token
// for an unmapped key (code 0) so save() can reproduce it.
function parseKey(value) {
  var out = { code: 0, ctrl: 0, alt: 0, shift: 0, raw: null };
  value = (value == null ? '' : String(value)).split(',')[0].trim();   // primary binding
  if (value === '' || value === 'None') return out;
  var parts = value.split('+');
  var base = parts.pop().trim();
  parts.forEach(function (m) { var f = MOD_TOKENS[m.trim()]; if (f) out[f] = 1; });
  if (/^[A-Za-z]$/.test(base)) out.code = base.toUpperCase().charCodeAt(0);
  else if (/^[0-9]$/.test(base)) out.code = base.charCodeAt(0);
  else if (SPECIAL_TO_VK[base] != null) out.code = SPECIAL_TO_VK[base];
  else out.raw = base;                        // unknown token -> preserve literally, code stays 0
  return out;
}

// Base key token for a VK code (letter / digit / SC2 special-name), or null if none maps.
function tokenOfVk(code) {
  if (code >= 65 && code <= 90) return String.fromCharCode(code);   // A-Z
  if (code >= 48 && code <= 57) return String.fromCharCode(code);   // 0-9
  return VK_TO_SPECIAL[code] || null;
}

// Render an editable bind back to an SC2 value string ('' = unbound). Modifiers use the game's
// canonical Control+Shift+Alt order (matches the order .SC2Hotkeys files are written in).
function formatKey(b) {
  var base = tokenOfVk(b.code);
  if (base == null) base = b.raw;
  if (base == null) return '';                                     // unbound
  var s = '';
  if (b.ctrl) s += 'Control+';
  if (b.shift) s += 'Shift+';
  if (b.alt) s += 'Alt+';
  return s + base;
}

// Everything after the first comma of a value (the alternate bindings), '' if none. SC2 allows
// several keys per command, e.g. `Larva=0,P,SemiColon` -> primary `0`, alternates `P,SemiColon`.
function altStr(value) {
  var i = String(value == null ? '' : value).indexOf(',');
  return i < 0 ? '' : String(value).slice(i + 1);
}

// Convert every base key token in an SC2 value string through a VK remap `m` (the QWERTY<->Dvorak
// map the layout toggle builds), preserving modifiers, the multi-bind (comma) structure, and any
// unknown token (e.g. LeftMouseButton) verbatim. Returns { value, n } with n tokens remapped.
function remapValueStr(value, m) {
  if (value == null || value === '') return { value: value, n: 0 };
  var n = 0;
  var parts = String(value).split(',').map(function (part) {
    var plus = part.split('+');
    var base = plus[plus.length - 1].trim();
    var vk = null;
    if (/^[A-Za-z]$/.test(base)) vk = base.toUpperCase().charCodeAt(0);
    else if (/^[0-9]$/.test(base)) vk = base.charCodeAt(0);
    else if (SPECIAL_TO_VK[base] != null) vk = SPECIAL_TO_VK[base];
    if (vk != null && m[vk] !== undefined) { plus[plus.length - 1] = tokenOfVk(m[vk]); n++; return plus.join('+'); }
    return part;
  });
  return { value: parts.join(','), n: n };
}

function sameKey(a, b) {
  return a.code === b.code && !!a.ctrl === !!b.ctrl && !!a.alt === !!b.alt && !!a.shift === !!b.shift;
}

// ===== .SC2Hotkeys codec =========================================================
// Preserves [Settings] and [Hotkeys] bodies verbatim and re-emits [Commands] from the current
// override set.  Parse tolerates missing sections and either newline style.
function parse(text) {
  var eol = text.indexOf('\r\n') >= 0 ? '\r\n' : '\n';
  var lines = text.split(/\r?\n/);
  var section = '';
  var res = { settings: [], hotkeys: {}, hotkeysOrder: [], commands: {}, order: [], eol: eol };
  lines.forEach(function (line) {
    var s = line.trim();
    var sm = /^\[(.+)\]$/.exec(s);
    if (sm) { section = sm[1].toLowerCase(); return; }
    if (section === 'settings') { res.settings.push(line); return; }
    var eq, name;
    if (section === 'hotkeys') {
      eq = line.indexOf('='); if (eq < 0) return;
      name = line.slice(0, eq).trim(); if (!name) return;
      if (!(name in res.hotkeys)) res.hotkeysOrder.push(name);
      res.hotkeys[name] = line.slice(eq + 1).trim();
    } else if (section === 'commands') {
      eq = line.indexOf('='); if (eq < 0) return;
      name = line.slice(0, eq).trim(); if (!name) return;
      if (!(name in res.commands)) res.order.push(name);
      res.commands[name] = line.slice(eq + 1).trim();
    }
  });
  return res;
}

function trimBlock(arr) {                       // drop leading/trailing blank lines of a preserved body
  var a = arr.slice();
  while (a.length && a[0].trim() === '') a.shift();
  while (a.length && a[a.length - 1].trim() === '') a.pop();
  return a;
}

function unparse(raw, hotkeyLines, commandLines) {
  var eol = (raw && raw.eol) || '\r\n';
  var out = ['[Settings]'];
  out = out.concat(raw ? trimBlock(raw.settings) : []);
  out.push('');
  out.push('[Hotkeys]');
  out = out.concat(hotkeyLines);
  out.push('');
  out.push('[Commands]');
  out = out.concat(commandLines);
  return out.join(eol) + eol;
}

// ===== dataset (defaults / names / grouping / positions / icons) =================
// data/sc2.json: { units: id -> {id, name, qualifier, race, cards:[{index, buttons:[{command,
// name, key, row, col, universal, icon}]}]} }.  data/sc2_icons.json (as d.icons): command -> url.
var CARD_COLS = 5, CARD_ROWS = 3;               // SC2 command card is 5 wide x 3 tall
var DATA = null;
var ICONS = {};
var RECOMMENDED = null;   // bundled recommended layout { name, text } (a .SC2Hotkeys profile), or null
var TEMPLATES = {};   // outName -> binding template {name, command, universal, def:{code,...}}
var OCC = [];         // one entry per on-card button occurrence -> a record
var CTX_LABEL = {};   // context -> display group label (unit + sub-card)

var RACE_FILTER = { Terran: 'terran', Protoss: 'protoss', Zerg: 'zerg' };
var RACE_RANK = { terran: 0, protoss: 1, zerg: 2 };

// The generic movement/attack commands sit on every unit card; rather than repeat them per unit
// they show once in a shared "Unit Commands" group. The attack variants (AttackWorker, ...) are the
// same in-game hotkey as Attack (a .SC2Hotkeys file only ever has `Attack`), so they fold into it.
var MOVEMENT = { Move: 1, Stop: 1, MoveHoldPosition: 1, MovePatrol: 1, Attack: 1, Cancel: 1 };
var MOVE_NAMES = { Move: 'Move', Stop: 'Stop', MoveHoldPosition: 'Hold Position',
  MovePatrol: 'Patrol', Attack: 'Attack', Cancel: 'Cancel' };
var ATTACK_ALIAS = { AttackWorker: 'Attack', AttackRedirect: 'Attack', AttackStructure: 'Attack',
  AttackBuilding: 'Attack', AttackBuildingPFort: 'Attack', AttackGhost: 'Attack',
  AttackWarpPrism: 'Attack', AcquireMove: 'Attack' };
// Commands shown only while a structure is under construction (shared across every building).
var CONSTRUCTION = { Halt: 1, CancelBuilding: 1, SelectBuilder: 1 };
var UNITCMD_GROUP = 'Unit Commands';
var CONSTRUCTION_LABEL = 'Under Construction';
var CARD_MOVES = {};       // ctx -> { movementCommand: 1 } physically on that card (for conflicts)
var MODELED_NAMES = {};    // every .SC2Hotkeys output-name we model (for save-time preservation)

// ===== global hotkeys (the [Hotkeys] section: control groups, camera, chat, ...) =====
// These aren't on any command card; they group by family and share one 'global' conflict scope.
// `def` holds the Standard-profile default where it's well-known (control groups, subgroup, chat,
// menu); the rest default unbound (the game leaves many blank, and a loaded file supplies its own).
var GLOBALS = [];          // [{ name, group, label, def }]
var GLOBAL_NAMES = {};     // name -> 1 (every [Hotkeys] name we model)
// The 10 control groups each expose the same five actions on the same number key, separated only by
// modifier (Select = bare, Create = Control+, Add = Shift+, and the two Steal variants). They live in
// one "Control Groups" group: in "prefer keyboard binds" mode each number key carries the stack (the
// n/N badge cycles them), and dragging a number key moves the whole stack together (mods preserved).
function buildGlobals() {
  GLOBALS = []; GLOBAL_NAMES = {};
  var num = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'];
  function add(name, group, label, def) {
    GLOBALS.push({ name: name, group: group, label: label, def: def || '' });
    GLOBAL_NAMES[name] = 1;
  }
  for (var i = 0; i < 10; i++) {
    var n = i + 1;
    add('ControlGroupRecall' + i, 'Control Groups', 'Select Group ' + n, num[i]);
    add('ControlGroupAssign' + i, 'Control Groups', 'Create Group ' + n, 'Control+' + num[i]);
    add('ControlGroupAppend' + i, 'Control Groups', 'Add to Group ' + n, 'Shift+' + num[i]);
    add('ControlGroupAssignAndSteal' + i, 'Control Groups', 'Create+Steal Group ' + n, '');
    add('ControlGroupAppendAndSteal' + i, 'Control Groups', 'Add+Steal Group ' + n, '');
  }
  for (var j = 0; j < 8; j++) {
    add('CameraView' + j, 'Camera', 'Camera Location ' + j, '');
    add('CameraSave' + j, 'Camera', 'Save Camera ' + j, '');
  }
  add('CameraCenter', 'Camera', 'Center Camera', '');
  add('CameraFollow', 'Camera', 'Follow Unit', '');
  add('CameraTurnLeft', 'Camera', 'Rotate Camera Left', '');
  add('CameraTurnRight', 'Camera', 'Rotate Camera Right', '');
  add('TownCamera', 'Camera', 'Go To Base Camera', '');
  add('ArmySelect', 'Selection', 'Select All Army', '');
  add('IdleWorker', 'Selection', 'Select Idle Worker', '');
  add('SubgroupNext', 'Selection', 'Next Subgroup', 'Tab');
  add('SubgroupPrev', 'Selection', 'Previous Subgroup', 'Shift+Tab');
  add('TargetChoose', 'Selection', 'Choose Target', '');
  add('WarpIn', 'Selection', 'Warp In', '');
  add('AlertRecall', 'Selection', 'Go To Last Alert', '');
  add('ChatDefault', 'Communication', 'Chat', 'Enter');
  add('ChatAllies', 'Communication', 'Chat to Allies', '');
  add('ChatIndividual', 'Communication', 'Whisper Player', '');
  add('ChatRecipient', 'Communication', 'Cycle Chat Recipient', '');
  add('QuickPing', 'Communication', 'Ping', '');
  add('MinimapPing', 'Communication', 'Minimap Ping', '');
  add('StatusAll', 'Interface', 'Show All Life Bars', '');
  add('StatusAlly', 'Interface', 'Show Ally Life Bars', '');
  add('StatusEnemy', 'Interface', 'Show Enemy Life Bars', '');
  add('StatusOwner', 'Interface', 'Show Own Life Bars', '');
  add('MinimapColors', 'Interface', 'Toggle Minimap Colors', '');
  add('MinimapTerrain', 'Interface', 'Toggle Minimap Terrain', '');
  add('GameTooltipsOn', 'Interface', 'Toggle Tooltips', '');
  add('FPS', 'Interface', 'Toggle FPS Display', '');
  add('Music', 'Interface', 'Toggle Music', '');
  add('Sound', 'Interface', 'Toggle Sound', '');
  add('PTT', 'Interface', 'Push To Talk', '');
  add('MenuGame', 'Game Menu', 'Open Menu', 'F10');
  add('MenuAchievements', 'Game Menu', 'Achievements', '');
  add('QuickSave', 'Game Menu', 'Quick Save', '');
  for (var c = 0; c < 4; c++) add('CommanderAbility' + c, 'Commander (Co-op)', 'Commander Ability ' + (c + 1), '');
}

// The in-game editor writes the [Hotkeys] section in a fixed, hand-authored enumeration order -- NOT
// alphabetical (audio toggles first, StatusOwner before StatusAlly, CameraSave/CameraView last) and
// unrelated to our on-screen GLOBALS grouping. Emitting our own order made a profile "move" the first
// time it was re-saved in the game (spurious diff noise on round-trip). This list is that exact order,
// captured from a game-saved profile; it covers every global we model. ([Commands], by contrast, the
// game writes in plain name order -- see saveDoc.)
var HOTKEYS_ORDER = [
  'FPS', 'Music', 'Sound', 'PTT', 'ChatAllies', 'ChatDefault',
  'ChatIndividual', 'ChatRecipient', 'MenuAchievements', 'MenuGame', 'AlertRecall', 'ArmySelect',
  'CameraCenter', 'CameraFollow', 'CameraTurnLeft', 'CameraTurnRight', 'CommanderAbility0', 'CommanderAbility1',
  'CommanderAbility2', 'CommanderAbility3', 'ControlGroupAppend0', 'ControlGroupAppend1', 'ControlGroupAppend2', 'ControlGroupAppend3',
  'ControlGroupAppend4', 'ControlGroupAppend5', 'ControlGroupAppend6', 'ControlGroupAppend7', 'ControlGroupAppend8', 'ControlGroupAppend9',
  'ControlGroupAppendAndSteal0', 'ControlGroupAppendAndSteal1', 'ControlGroupAppendAndSteal2', 'ControlGroupAppendAndSteal3', 'ControlGroupAppendAndSteal4', 'ControlGroupAppendAndSteal5',
  'ControlGroupAppendAndSteal6', 'ControlGroupAppendAndSteal7', 'ControlGroupAppendAndSteal8', 'ControlGroupAppendAndSteal9', 'ControlGroupAssign0', 'ControlGroupAssign1',
  'ControlGroupAssign2', 'ControlGroupAssign3', 'ControlGroupAssign4', 'ControlGroupAssign5', 'ControlGroupAssign6', 'ControlGroupAssign7',
  'ControlGroupAssign8', 'ControlGroupAssign9', 'ControlGroupAssignAndSteal0', 'ControlGroupAssignAndSteal1', 'ControlGroupAssignAndSteal2', 'ControlGroupAssignAndSteal3',
  'ControlGroupAssignAndSteal4', 'ControlGroupAssignAndSteal5', 'ControlGroupAssignAndSteal6', 'ControlGroupAssignAndSteal7', 'ControlGroupAssignAndSteal8', 'ControlGroupAssignAndSteal9',
  'ControlGroupRecall0', 'ControlGroupRecall1', 'ControlGroupRecall2', 'ControlGroupRecall3', 'ControlGroupRecall4', 'ControlGroupRecall5',
  'ControlGroupRecall6', 'ControlGroupRecall7', 'ControlGroupRecall8', 'ControlGroupRecall9', 'GameTooltipsOn', 'IdleWorker',
  'MinimapColors', 'MinimapPing', 'MinimapTerrain', 'QuickPing', 'QuickSave', 'StatusAll',
  'StatusOwner', 'StatusAlly', 'StatusEnemy', 'SubgroupNext', 'SubgroupPrev', 'TargetChoose',
  'TownCamera', 'WarpIn', 'CameraSave0', 'CameraSave1', 'CameraSave2', 'CameraSave3',
  'CameraSave4', 'CameraSave5', 'CameraSave6', 'CameraSave7', 'CameraView0', 'CameraView1',
  'CameraView2', 'CameraView3', 'CameraView4', 'CameraView5', 'CameraView6', 'CameraView7'
];
var HOTKEYS_RANK = {};
HOTKEYS_ORDER.forEach(function (n, i) { HOTKEYS_RANK[n] = i; });

// The game orders both sections by the entry name only (the text before '='), NOT the whole
// "name=value" line. Sorting whole lines misplaces names that are a prefix of another, since '='
// (0x3D) sorts after '/' (0x2F) and after digits: bare `Foo` would fall behind `Foo/Ctx`, and
// `Bar@1` behind `Bar@11`. Compare the name column to match the engine.
function nameOf(line) { var i = line.indexOf('='); return i < 0 ? line : line.slice(0, i); }
function cmpByName(a, b) { a = nameOf(a); b = nameOf(b); return a < b ? -1 : a > b ? 1 : 0; }
// [Hotkeys]: canonical enumeration order; any name we don't model sorts after, by name.
function cmpHotkeyLine(a, b) {
  var an = nameOf(a), bn = nameOf(b);
  var ai = HOTKEYS_RANK[an], bi = HOTKEYS_RANK[bn];
  if (ai == null) ai = HOTKEYS_ORDER.length;
  if (bi == null) bi = HOTKEYS_ORDER.length;
  if (ai !== bi) return ai - bi;
  return an < bn ? -1 : an > bn ? 1 : 0;
}

// A "binding" is one editable hotkey. It is keyed so that (a) a Universal command is ONE binding
// shared wherever it appears (edit once, applies everywhere), and (b) within one display group a
// command carried by several unit-forms (Overlord vs OverlordTransport) is ONE row -- yet it still
// remembers every .SC2Hotkeys name it covers, so saving writes them all. Grouping/conflict scope is
// the actual card (unit + CardId), except movement -> shared "Unit Commands" and construction-state
// buttons -> shared "Under Construction".
function setData(d) {
  DATA = (d && d.units) ? d.units : null;
  ICONS = (d && d.icons) || {};
  RECOMMENDED = (d && d.recommended) || null;
  TEMPLATES = {}; OCC = []; CTX_LABEL = {}; CARD_MOVES = {}; MODELED_NAMES = {};
  buildGlobals();
  if (!DATA) return;

  function template(key, command, universal, def, outName, displayName) {
    var t = TEMPLATES[key];
    if (!t) t = TEMPLATES[key] = { key: key, command: command, universal: !!universal,
      def: def, name: displayName, saveNames: [] };
    if (t.saveNames.indexOf(outName) < 0) { t.saveNames.push(outName); MODELED_NAMES[outName] = 1; }
    return t;
  }

  var emitted = {};
  Object.keys(DATA).forEach(function (uid) {
    var u = DATA[uid];
    var race = RACE_FILTER[u.race];
    if (!race || u.playable === false || u.melee === false) return;
    (u.cards || []).forEach(function (card) {
      var group = (u.name || uid) + (card.label ? ' — ' + card.label : '');
      var ctx = 'u:' + uid + ':' + card.id;
      CTX_LABEL[ctx] = group;
      (card.buttons || []).forEach(function (b) {
        var command = ATTACK_ALIAS[b.command] || b.command;      // fold attack variants into Attack
        var universal = !!b.universal || command !== b.command;   // Attack is universal
        var name = MOVE_NAMES[command] || b.name;
        // route to display group + conflict scope
        var rgroup, rctx;
        if (MOVEMENT[command]) {
          rgroup = UNITCMD_GROUP; rctx = 'unitcmd';
          (CARD_MOVES[ctx] = CARD_MOVES[ctx] || {})[command] = 1;   // record it's on this real card
        } else if (CONSTRUCTION[command] || b.type === 'SelectBuilder') {
          rgroup = CONSTRUCTION_LABEL; rctx = 'construction';
        } else {
          rgroup = group; rctx = ctx;
        }
        CTX_LABEL[rctx] = rgroup;
        var outName = universal ? command : (command + '/' + u.qualifier);
        var key = universal ? ('U|' + command) : ('N|' + rgroup + '|' + command);
        template(key, command, universal, parseKey(b.key), outName, name);
        var ek = rgroup + '\x00' + key;
        if (emitted[ek]) return; emitted[ek] = 1;                  // one row per binding per group
        OCC.push({ key: key, unit: uid, ctx: rctx, group: rgroup, race: race,
          kind: u.kind || 'unit', command: command, resolved: b.shares || command,
          name: name, slot: b.row * CARD_COLS + b.col });
      });
    });
  });
}

// ===== doc <-> engine binds ======================================================
// The opaque doc is { binds, byName, raw, name }.  A bind is one editable hotkey (a template made
// live), carrying mutable engine state (code/ctrl/alt/shift) plus its defaults and file-origin.
function buildDoc(raw, name) {
  var overrides = (raw && raw.commands) || {};
  var binds = [];
  var byKey = {};
  var nextId = 1;
  Object.keys(TEMPLATES).forEach(function (key) {
    var t = TEMPLATES[key];
    // Load the current key from the first of this binding's names present in the file (its primary);
    // remember each name's original string so unchanged ones round-trip verbatim (incl. multi-key).
    var loaded = null, loadedValues = {};
    t.saveNames.forEach(function (nm) {
      if (nm in overrides) { loadedValues[nm] = overrides[nm]; if (loaded == null) loaded = overrides[nm]; }
    });
    var cur = (loaded != null) ? parseKey(loaded) : t.def;
    var alts = (loaded != null) ? altStr(loaded) : '';
    var bind = {
      id: nextId++, key: key, command: t.command, universal: t.universal, saveNames: t.saveNames,
      code: cur.code, ctrl: cur.ctrl, alt: cur.alt, shift: cur.shift, raw: cur.raw,
      origCode: cur.code, origCtrl: cur.ctrl, origAlt: cur.alt, origShift: cur.shift,
      alts: alts, origAlts: alts,
      def: t.def, loadedValues: loadedValues
    };
    binds.push(bind);
    byKey[key] = bind;
  });
  // Global hotkeys ([Hotkeys] section): one bind each, value from the loaded file or the default.
  var hk = (raw && raw.hotkeys) || {};
  GLOBALS.forEach(function (g) {
    var loaded = (g.name in hk) ? hk[g.name] : null;
    var def = parseKey(g.def);
    var cur = (loaded != null) ? parseKey(loaded) : def;
    var alts = (loaded != null) ? altStr(loaded) : '';
    var bind = {
      id: nextId++, key: 'G|' + g.name, command: null, universal: false, global: true,
      hotkeyName: g.name, saveNames: [],
      code: cur.code, ctrl: cur.ctrl, alt: cur.alt, shift: cur.shift, raw: cur.raw,
      origCode: cur.code, origCtrl: cur.ctrl, origAlt: cur.alt, origShift: cur.shift,
      alts: alts, origAlts: alts,
      def: def, loadedValues: (loaded != null ? { hk: loaded } : {})
    };
    binds.push(bind);
    byKey[bind.key] = bind;
  });
  return { binds: binds, byKey: byKey, raw: raw, name: name || null };
}

function loadFile(file, _prev) {
  return file.text().then(function (text) { return buildDoc(parse(text), null); });
}
function loadDefault(_prev) { return Promise.resolve(buildDoc(null, null)); }
// Start from the bundled recommended layout (HotkeyFiles/RecommendedLayout/, inlined by the
// generator) -- parse its .SC2Hotkeys text like a loaded file, and name the profile after it.
function loadRecommended(_prev) {
  if (!(RECOMMENDED && RECOMMENDED.text)) return Promise.reject(new Error('no bundled recommended layout'));
  return Promise.resolve(buildDoc(parse(RECOMMENDED.text), RECOMMENDED.name || null));
}

function edited(b) {
  return !(b.code === b.origCode && !b.ctrl === !b.origCtrl
    && !b.alt === !b.origAlt && !b.shift === !b.origShift);
}
function altsChanged(b) { return (b.alts || '') !== (b.origAlts || ''); }
// A bind's full value string for saving: its (edited) primary key plus any alternate bindings.
function bindValue(b) {
  var pk = formatKey(b);
  if (!b.alts) return pk;
  return pk ? pk + ',' + b.alts : b.alts;
}

// Layout conversion beyond each modeled bind's primary key (which page.html's generic remap already
// handles): the alternate bindings, plus every [Commands]/[Hotkeys] line we don't model (co-op and
// campaign hotkeys, preserved verbatim otherwise). Ensures the whole file is converted, not just the
// keys editable on screen. `m` is the same VK remap the layout toggle passes to the generic remap.
function remapExtra(doc, m) {
  if (!doc) return 0;
  var n = 0;
  doc.binds.forEach(function (b) {
    if (b.alts) { var r = remapValueStr(b.alts, m); b.alts = r.value; n += r.n; }
  });
  var raw = doc.raw;
  if (raw) {
    raw.order.forEach(function (nm) {
      if (MODELED_NAMES[nm]) return;                 // modeled names convert via their bind
      var r = remapValueStr(raw.commands[nm], m); raw.commands[nm] = r.value; n += r.n;
    });
    raw.hotkeysOrder.forEach(function (nm) {
      if (GLOBAL_NAMES[nm]) return;
      var r = remapValueStr(raw.hotkeys[nm], m); raw.hotkeys[nm] = r.value; n += r.n;
    });
  }
  return n;
}
function saveDoc(doc, name) {
  // .SC2Hotkeys stores only differences from the game default. Each binding writes all the names it
  // covers (Overlord + OverlordTransport). An edited binding writes its single new key; an untouched
  // one preserves the file's original value verbatim (multi-key values like `Larva=0,P,SemiColon`);
  // anything reverted to default is dropped.
  var lines = [];
  var emitted = {};
  doc.binds.forEach(function (b) {
    if (b.global) return;                       // globals handled below (they go in [Hotkeys])
    var dirty = edited(b) || altsChanged(b);    // primary rebound, or alternates converted/changed
    b.saveNames.forEach(function (nm) {
      if (emitted[nm]) return;
      if (dirty) {
        // drop only a binding reverted entirely to its (alternate-less) default
        if (!sameKey(b, b.def) || b.alts) {
          var v = bindValue(b);
          if (v) { lines.push(nm + '=' + v); emitted[nm] = 1; }
        }
      } else if (nm in b.loadedValues) {
        lines.push(nm + '=' + b.loadedValues[nm]); emitted[nm] = 1;
      }
    });
  });
  // Preserve the file's overrides for commands we don't model (co-op/campaign hotkeys).
  if (doc.raw) doc.raw.order.forEach(function (nm) {
    if (emitted[nm] || MODELED_NAMES[nm]) return;
    lines.push(nm + '=' + doc.raw.commands[nm]); emitted[nm] = 1;
  });
  lines.sort(cmpByName);

  // [Hotkeys] section: write every bound global (edited -> single key; untouched -> the file's
  // original value verbatim), then preserve any [Hotkeys] name we don't model.
  var hkLines = [];
  var hkEmitted = {};
  doc.binds.forEach(function (b) {
    if (!b.global) return;
    var dirty = edited(b) || altsChanged(b);
    var val = dirty ? bindValue(b) : (('hk' in b.loadedValues) ? b.loadedValues.hk : formatKey(b));
    if (val) { hkLines.push(b.hotkeyName + '=' + val); hkEmitted[b.hotkeyName] = 1; }
  });
  if (doc.raw) doc.raw.hotkeysOrder.forEach(function (nm) {
    if (hkEmitted[nm] || GLOBAL_NAMES[nm]) return;
    hkLines.push(nm + '=' + doc.raw.hotkeys[nm]); hkEmitted[nm] = 1;
  });
  hkLines.sort(cmpHotkeyLine);
  var text = unparse(doc.raw, hkLines, lines);
  var fname = (name && name.trim() ? name.trim() : 'Custom') + '.SC2Hotkeys';
  return Promise.resolve({ blob: new Blob([text], { type: 'text/plain' }), filename: fname,
    note: 'Downloaded ' + fname + ' — put it in Documents\\StarCraft II\\Hotkeys and pick it in the game\'s Hotkeys menu.' });
}

// ===== records ===================================================================
// One record per on-card button occurrence.  A Universal command that sits on several units'
// cards yields several records that share one binding `id`, so an edit propagates to all and the
// engine never conflicts it with itself across cards.
function bindings(doc) {
  if (!doc) return [];
  if (!DATA) {                                  // dev / no dataset: flat list by raw name
    return doc.binds.map(function (b) {
      return { e: b, id: b.id, unit: null, ctx: '', name: b.name, group: 'Hotkeys',
        slot: null, command: b.command, hidden: false, campaign: false };
    });
  }
  var recs = [];
  OCC.forEach(function (o) {
    var b = doc.byKey[o.key]; if (!b) return;
    recs.push({ e: b, id: b.id, unit: o.unit, ctx: o.ctx, race: o.race, kind: o.kind, name: o.name,
      group: o.group, slot: o.slot, command: o.command, resolved: o.resolved, hidden: false, campaign: false });
  });
  GLOBALS.forEach(function (g) {
    var b = doc.byKey['G|' + g.name]; if (!b) return;
    recs.push({ e: b, id: b.id, unit: null, ctx: 'global', race: null, name: g.label,
      group: g.group, slot: null, command: null, global: true, hidden: false, campaign: false });
  });
  // Alphabetical within each group (the engine keeps this order per group; groups are re-sorted by
  // groupKey at render time).
  recs.sort(function (a, b) { return a.name.localeCompare(b.name); });
  return recs;
}

function forEachEntry(doc, fn) { if (doc) doc.binds.forEach(fn); }

// ===== grouping / conflicts ======================================================
function groupOf(r) { return r.group; }
// conflict scope = the exact command card the record sits on (unit + CardId).
function context(r) { return r.ctx; }
function ctxLabel(ctx) { return CTX_LABEL[ctx] || ''; }
// Records already share a key-combo (engine bucketed) and aren't the same binding (same id skipped).
// Two commands clash iff they occupy the same command card. The shared "Unit Commands" (movement)
// set sits on every mobile unit's card, so a movement command also clashes with a unit-specific
// command whose card actually carries that movement command (CARD_MOVES). A hotkey reused on
// different cards, or two buttons in the SAME slot (mutually-exclusive states -- Salvage vs Halt, a
// morph and its reverse), is not a conflict.
function classify(ra, rb) {
  var A = ra.ctx, B = rb.ctx;
  // Two records that resolve to the SAME underlying game hotkey are one hotkey to the engine and
  // never conflict -- e.g. the Oracle's Pulsar-beam attack (OracleAttack) reuses Attack's hotkey, so
  // sharing a key with the movement Attack is by design, not a clash.
  if (ra.resolved && rb.resolved && ra.resolved === rb.resolved) return null;
  if (A === 'unitcmd' && B === 'unitcmd') return { sev: 'confirmed' };     // same shared card
  if (A === 'unitcmd' || B === 'unitcmd') {
    var mv = A === 'unitcmd' ? ra : rb, other = A === 'unitcmd' ? rb : ra;
    if (other.ctx === 'construction') return null;
    var moves = CARD_MOVES[other.ctx];
    return (moves && moves[mv.command]) ? { sev: 'confirmed' } : null;     // movement on that card
  }
  if (A !== B) return null;
  if (ra.slot != null && ra.slot === rb.slot) return null;   // same slot = mutually exclusive
  return { sev: 'confirmed' };
}
function recName(r) { return r.name; }

// ===== on-card position + icon (read-only; SC2 positions are fixed by the game) ==
function slotOf(r) { return (r && r.slot != null) ? r.slot : null; }
function iconOf(r) { var c = r && r.command; var u = c && ICONS[c]; return u || null; }

// ===== race filter + column categories ===========================================
var FILTERS = [
  { id: 'terran', label: 'Terran' }, { id: 'protoss', label: 'Protoss' }, { id: 'zerg', label: 'Zerg' }
];
var SHARED_CTX = { unitcmd: 1, construction: 1, global: 1 };   // race-independent -> show under all
function recFilters(r) { return SHARED_CTX[r.ctx] ? ['terran', 'protoss', 'zerg'] : [r.race]; }
function pad2(n) { return (n < 10 ? '0' : '') + n; }
// Column categories are by TYPE (like Warcraft III): General (movement/cancel + construction),
// Units, Buildings, then Global (the [Hotkeys] set) last.  Race is the filter, not a column.
function catOf(r) {
  if (r.ctx === 'global') return 3;
  if (r.ctx === 'unitcmd' || r.ctx === 'construction') return 0;
  return r.kind === 'building' ? 2 : 1;
}
function groupKey(r) {
  var cat = pad2(catOf(r));
  // Within Global, lead with "Control Groups", then the remaining families alphabetically.
  if (r.ctx === 'global') return cat + '|' + (r.group === 'Control Groups' ? '0' : '1') + r.group;
  return cat + '|' + r.group;
}
function groupCategory(r) { return pad2(catOf(r)); }
var CAT_TITLE = { '00': 'General', '01': 'Units', '02': 'Buildings', '03': 'Global' };
function categoryTitle(id) { return CAT_TITLE[id] || ''; }

function fileStatus(doc) {
  return doc ? '<span class="chip ok">✓ hotkeys loaded</span>'
             : '<span class="chip need">⬆ load a .SC2Hotkeys file</span>';
}

// ===== register + wire into the engine's GAME interface ==========================
GAMES.starcraft2 = {
  meta: {
    name: 'StarCraft II',
    blurb: 'Works with StarCraft II multiplayer .SC2Hotkeys files (Legacy of the Void).',
    fileLabel: 'Load .SC2Hotkeys',
    defaultsLabel: 'Load defaults',
    filterLabel: 'Race:',
    fileAccept: '.SC2Hotkeys',
    multiple: false,
    usesProfileName: true,          // download is named <profile>.SC2Hotkeys
    cardCols: CARD_COLS, cardRows: CARD_ROWS,
    pathHelp:
      '<div class="helpsubhead">To get started</div>'
      + '<p>Load a <code>.SC2Hotkeys</code> profile, or click '
      + '<b>Load defaults</b> to start from the standard multiplayer defaults.</p>'
      + '<div class="helpsubhead">Where they live</div>'
      + '<p><code>Documents\\StarCraft II\\Hotkeys\\</code>.</p>'
      + '<p>Edit here, download the file, drop it in that folder, and select the profile in the '
      + 'game\'s <i>Options → Hotkeys</i> menu.</p>',
    placeholder: 'Load a <code>.SC2Hotkeys</code> file to view and edit StarCraft II hotkeys, '
      + 'or click <b>Load defaults</b> to start from the standard multiplayer set.',
    applyNote: 'Save the .SC2Hotkeys file into Documents\\StarCraft II\\Hotkeys, then select it '
      + 'in the game\'s Hotkeys options.'
  },
  codec: { load: loadFile, loadDefault: loadDefault, loadRecommended: loadRecommended, save: saveDoc, parse: parse, unparse: unparse },
  input: { vkLabels: {}, mouseButtons: [] },
  setData: setData,
  hasRecommended: function () { return !!(RECOMMENDED && RECOMMENDED.text); },  // gate the "try my layout" box on a bundled layout
  fileStatus: fileStatus,
  bindings: bindings,
  forEachEntry: forEachEntry,
  remapExtra: remapExtra,        // convert alternates + unmodeled [Commands]/[Hotkeys] on a layout switch
  groupOf: groupOf,
  context: context,
  classify: classify,
  recName: recName,
  icon: iconOf,
  slot: slotOf,
  baseName: function (r) { return r && r.name ? r.name : ''; },
  ctxLabel: ctxLabel,
  filters: FILTERS,
  recFilters: recFilters,
  groupKey: groupKey,
  groupCategory: groupCategory,
  categoryTitle: categoryTitle
};

})();
